server:
  port: 8081
spring:
  datasource:
    username: root
    password: Hi.1234567
    url: jdbc:mysql://192.168.1.100:3306/woody
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema-username: root
    schema-password: Hi.1234567
    data-username: root
    data-password: Hi.1234567
    platform: mysql
    schema:
      - classpath:sql/schema-all.sql
    initialization-mode: always
    sql-script-encoding: utf-8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: DatebookHikariCP
      #连接池最大连接数，默认是10
      maximum-pool-size: 15
      #最小空闲连接数量
      minimum-idle: 5
      #从池返回的连接默认自动提交
      auto-commit: true
      #空闲连接最大时间，10秒
      idle-timeout: 10000
      #池中连接的最长生命周期
      max-lifetime: 1800000
      #数据库连接的超时时间
      connection-timeout: 30000
      connection-test-query: SELECT 1
